# This schema has been generated ...
# The order in which the attributes are declared is important,
# it specify the attribute xxx...
identifier = "id"

[attributes.id]
displayed = true

[attributes.title]
displayed = true
indexed = true

[attributes.overview]
displayed = true
indexed = true

[attributes.release_date]
displayed = true

[attributes.poster]
displayed = true
